Fix NullPointerException for DatabaseConnection returned after days of uptime

[2014-07-25 11:05:38] java.lang.NullPointerException
	at bitbot.external.MicrosoftAzureExt.btce_Select_Graph_Data(MicrosoftAzureExt.java:50)
	at bitbot.cache.tickers.TickerCacheTask$TickerCacheTask_MSSql.run(TickerCacheTask.java:617)
	at bitbot.server.threads.LoggingSaveRunnable.run(LoggingSaveRunnable.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
